const DISPLAY_LABELS: Record<string, string> = {
  animation: "动画",
  background: "背景",
  blue: "蓝色",
  blur: "模糊",
  button: "按钮",
  buttons: "按钮",
  campaign: "活动页",
  "campaign-page": "活动页",
  card: "卡片",
  cards: "卡片",
  checkbox: "选择控件",
  checkboxes: "选择控件",
  checklist: "选择控件",
  "call to action": "转化入口",
  circle: "圆形",
  click: "点击",
  cta: "转化入口",
  dark: "深色",
  ecommerce: "电商",
  expressive: "强表现",
  explosion: "爆炸",
  fade: "淡入",
  flat: "扁平",
  form: "表单",
  "gift-rain": "礼物雨",
  glass: "毛玻璃",
  glow: "发光",
  gradient: "渐变",
  gray: "灰色",
  green: "绿色",
  hero: "首屏",
  hover: "悬停",
  interaction: "交互",
  landing: "落地页",
  "landing-page": "落地页",
  layout: "布局",
  live: "直播间",
  load: "入场",
  loop: "循环",
  magnetic: "磁吸",
  marketing: "营销页",
  media: "媒体",
  micro: "微交互",
  "micro interaction": "微交互",
  "micro-interaction": "微交互",
  "mobile-page": "移动端页面",
  "mobile screen": "移动端页面",
  native: "内置",
  orange: "橙色",
  outline: "描边",
  "page-transition": "页面转场",
  particle: "粒子",
  pill: "胶囊",
  premium: "精致",
  promotion: "活动页",
  purple: "紫色",
  rainbow: "彩虹",
  red: "红色",
  reveal: "入场",
  rotate: "旋转",
  "right-to-left": "右进左出",
  saas: "软件服务",
  scale: "缩放",
  shadow: "阴影",
  slide: "位移",
  slow: "慢速",
  "screen-transition": "页面转场",
  subtle: "克制",
  tech: "科技感",
  text: "文字",
  transform: "变换",
  transition: "过渡",
  fast: "快速",
  normal: "常规",
  "left-to-right": "左进右出",
  "top-to-bottom": "上进下出",
  "bottom-to-top": "下进上出",
  uploaded: "上传",
  violet: "紫色",
  white: "白色",
  workeasy: "工作易",
  "work easy": "工作易",
  yellow: "黄色"
};

export function displayLabel(value: string): string {
  const normalized = value.trim().toLowerCase();
  return DISPLAY_LABELS[normalized] ?? value;
}

export function displayLabels(values: string[]): string[] {
  return [
    ...new Set(
      values
        .map(displayLabel)
        .map((value) => value.trim())
        .filter(Boolean)
    )
  ];
}
